redis:
  build: redis/
appserver:
  env_file:
    - "secrets.env"
  build: appserver/
  links:
    - redis
webproxy:
  build: webproxy/
  links:
    - appserver
  volumes_from:
    - static
    - appserver                 # get cache from appserver
  ports:
    - "80:80"
    - "443:443"
static:
  build: static-files/
  volumes:
    - static-files/src/:/home/app/src/:ro
