# Temporary dev-environment setup.  These need to get cleaned up
matchdb:
  image: mongo
  volumes:
    - cache/matchdb:/data/db
riotambassador:
  build: riotAmbassador/
# RabbitMQ instance for storing messaging related to matches
matchcollectorqueue:
  build: matchCollector/rabbitmq/
  hostname: matchcollectorqueue
  volumes:
    - cache/matchCollectorQueue:/var/lib/rabbitmq/
  # management port SHOULD NOT BE EXPOSED TO OUTSIDE WORLD
  ports:
    - "15672:15672"
# Endpoint to send new match IDs to
matchcollectorgetter:
  build: matchCollector/matchGetter/
  environment:
    - DEBUG=rabbit-worker
  volumes:
    - matchCollector/matchGetter/src:/home/app/src/
  links:
    - matchcollectorqueue:matchcollectorqueue
  ports:
    - "8002:8000"
# Collector of the riot seed data
matchcollectorseedgetter:
  build: matchCollector/seedGetter/
  environment:
    - DEBUG=rabbit-worker
  links:
    - matchcollectorqueue:matchcollectorqueue
  volumes:
    - matchCollector/seedGetter/src:/home/app/src/
  ports:
    - "8003:8000"
# Stores matches collected from the seed data or otherwise
matchcollectorstorer:
  build: matchCollector/matchStorer
  environment:
    - DEBUG=rabbit-worker
  links:
    - matchcollectorqueue:matchcollectorqueue
    - matchdb:mongo
  volumes:
    - matchCollector/matchStorer/src:/home/app/src/
# Looks up new match IDs in the queue up
matchcollectorlookup:
  build: matchCollector/matchLookup/
  volumes:
    - matchCollector/matchLookup/src:/home/app/src/
  environment:
    - DEBUG=rabbit-worker
  links:
    - matchcollectorqueue:matchcollectorqueue
    - riotambassador:riotambassador