# Temporary dev-environment setup.  These need to get cleaned up
riotambassador:
  build: riotAmbassador/
matchcollectorqueue:
  build: matchCollector/rabbitmq/
  hostname: matchcollectorqueue
  volumes:
    - matchCollector/queue:/var/lib/rabbitmq/
matchcollectorgetter:
  build: matchCollector/matchGetter/
  environment:
    - DEBUG=rabbit-worker
  volumes:
    - matchCollector/matchGetter/src:/home/app/src/
  links:
    - matchcollectorqueue:matchcollectorqueue
  # ports:
  #   - "8002:8000"
matchcollectorlookup:
  build: matchCollector/matchLookup/
  volumes:
    - matchCollector/matchLookup/src:/home/app/src/
  environment:
    - DEBUG=rabbit-worker
  links:
    - matchcollectorqueue:matchcollectorqueue
    - riotambassador:riotambassador