# Example docker-compose for the old version of this app
# TODO: this needs to be cleaned up real bad
urf2015db:
  image: mongo
  volumes:
    - /mnt/urfdb/:/data/db/
riotambassador:
  build: riotAmbassador/
# matchgetter:
#  build: matchGetter/
#  links:
#    - riotambassador
#    - urf2015db:mongo
# matchlookup:
#  build: matchLookup/
#  links:
#    - riotambassador
#    - urf2015db:mongo
summonerlookup:
  build: summonerLookup/
  volumes:
    - summonerLookup/src:/usr/src/app/mnt/:ro
  links:
    - riotambassador
    - urf2015db:mongo
backendambassador:
  build: backendAmbassador/
  links:
    - summonerlookup
    - staticgetter
    - webserver
  ports:
    - "8000:8000"
# killcollector:
#   build: matchProcessor/ProcessMatchesIntoKillCollection/
#   links:
#     - urf2015db:mongo
# oddscollector:
#   build: matchProcessor/GetMatchupOdds/
#   links:
#     - urf2015db:mongo
# oddscalculator:
#   build: matchProcessor/ConvertKillDataToOdds/
#   links:
#     - urf2015db:mongo
# smoothksdata:
#   build: matchProcessor/SmoothKSData/
#   links:
#     - urf2015db:mongo
# avgitemcollector:
#   build: matchProcessor/GetAverageItemBuild/
#   links:
#     - urf2015db:mongo
# kscollector:
#   build: matchProcessor/GetKSPerChamp/
#   links:
#     - urf2015db:mongo
# multikillcollector:
#   build: matchProcessor/GetMultiKills/
#   links:
#     - urf2015db:mongo
# overallksoddscollector:
#   build: matchProcessor/GetOverallKSPerChamp/
#   links:
#     - urf2015db:mongo
# overallksgraphcollector:
#   build: matchProcessor/GetOverallKSPerChampTime/
#   links:
#     - urf2015db:mongo
# overallmatchupoddscollector:
#   build: matchProcessor/GetOverallMatchupOdds/
#   links:
#     - urf2015db:mongo
# overallmatchupgraphcollector:
#   build: matchProcessor/GetOverallMatchupOddsTime/
#   links:
#     - urf2015db:mongo
# snowballcollector:
#   build: matchProcessor/GetSnowballRating/
#   links:
#     - urf2015db:mongo
# itemmatchupcollector:
#   build: matchProcessor/GetStrongestItemAgainst/
#   links:
#     - urf2015db:mongo
webserver:
  build: matchProcessor/Webserver/
  links:
    - urf2015db:mongo
  ports:
    - "8001:8000"
staticgetter:
  build: staticGetter/
  links:
    - riotambassador
    - urf2015db:mongo
