# Basic working docker-compose.yml to be copied to docker-compose.yml and customized based on the environment
matchdb:
  image: mongo
  volumes:
    - cache/matchdb/:/data/db
riotambassador:
  build: riotAmbassador/
# General, shared rabbitmq instance
rabbitmq:
  build: rabbitmq/
  hostname: rabbit1
  volumes:
    - cache/rabbitmq:/var/lib/rabbitmq/
  # management port SHOULD NOT BE EXPOSED TO OUTSIDE WORLD
  ports:
    - "15672:15672"
# Endpoint to send new match IDs to
matchcollectorgetter:
  build: matchCollector/matchGetter/
  environment:
    - DEBUG=rabbit-worker
  volumes:
    - matchCollector/matchGetter/src:/home/app/src/
  links:
    - rabbitmq:matchcollectorqueue
  ports:
    - "8002:8000"
# Collector of the riot seed data
matchcollectorseedgetter:
  build: matchCollector/seedGetter/
  environment:
    - DEBUG=rabbit-worker
  links:
    - rabbitmq:matchcollectorqueue
  volumes:
    - matchCollector/seedGetter/src:/home/app/src/
  ports:
    - "8003:8000"
# Takes in data found by matchLookup and sends it off to other queues
matchcollectordistribute:
  build: matchCollector/matchDistribute
  environment:
    - DEBUG=rabbit-worker
  links:
    - rabbitmq:matchcollectorqueue
    - rabbitmq:summonercollectorqueue
    - rabbitmq:livedataqueue
  volumes:
    - matchCollector/matchDistribute/src:/home/app/src/
# Stores matches into mongo
matchcollectorstorer:
  build: matchCollector/matchStorer
  environment:
    - DEBUG=rabbit-worker
  links:
    - rabbitmq:matchcollectorqueue
    - matchdb:mongo 
  volumes:
    - matchCollector/matchStorer/src:/home/app/src/
# Looks up new match IDs in the queue up
matchcollectorlookup:
  build: matchCollector/matchLookup/
  volumes:
    - matchCollector/matchLookup/src:/home/app/src/
  environment:
    - DEBUG=rabbit-worker
    - NUM_WORKERS=3
  links:
    - rabbitmq:matchcollectorqueue
    - riotambassador:riotambassador
    - matchdb:mongo
    
# Summoner collectors
summonerdb:
  image: mongo
  volumes:
    - cache/summonerdb:/data/db
summonercollectorstorer:
  build: summonerCollector/summonerStorer
  environment:
    - DEBUG=rabbit-worker
  links:
    - rabbitmq:summonercollectorqueue
    - summonerdb:mongo
  volumes:
    - summonerCollector/summonerStorer/src:/home/app/src/
summonercollectorscheduler:
  build: summonerCollector/summonerScheduler
  environment:
    - DEBUG=rabbit-worker
  links:
    - rabbitmq:summonercollectorqueue
    - summonerdb:mongo
  volumes:
    - summonerCollector/summonerScheduler/src:/home/app/src/
summonercollectormatchlookup:
  build: summonerCollector/summonerMatchLookup
  environment:
    - DEBUG=rabbit-worker
    - NUM_WORKERS=3
  links:
    - rabbitmq:summonercollectorqueue
    - matchcollectorgetter:matchcollectorgetter
    - riotambassador:riotambassador
  volumes:
    - summonerCollector/summonerMatchLookup/src:/home/app/src/